### ISSUE TITLE
Kaggle TypeError: 'Plot' object is not callable

### ISSUE THREAD

**Issue by camenduru** [camenduru/MotionCtrl-colab#2]
```py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/tmp/ipykernel_638/3394077283.py", line 143, in fn_vis_camera
    fig = vis_camera(RT)
TypeError: 'Plot' object is not callable
```

**Comment by camenduru** [comment]
```py
!python 'main/evaluation/motionctrl_inference.py' \
--seed 1234 \
--ckpt_path './motionctrl.pth' \
--base "configs/inference/config_both.yaml" \
--savedir "./outputs/camera_motion/1234" \
--n_samples 5 \
--bs 1 --height 256 --width 256 \
--unconditional_guidance_scale 7.5 \
--ddim_steps 50 \
--ddim_eta 1.0 \
--condtype 'camera_motion' \
--cond_dir "examples/" \
```
